/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameboi;

/**
 *
 * @author Anant
 */
public class First_Difficulty extends javax.swing.JFrame {

    /**
     * Creates new form First_Difficulty
     */
    public First_Difficulty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Hard = new javax.swing.JLabel();
        Easy = new javax.swing.JLabel();
        medium = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Hard.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\redHard.jpg")); // NOI18N
        Hard.setLabelFor(Hard);
        Hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HardMouseClicked(evt);
            }
        });
        jPanel1.add(Hard);
        Hard.setBounds(400, 0, 301, 174);

        Easy.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\redEasy.jpg")); // NOI18N
        Easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EasyMouseClicked(evt);
            }
        });
        jPanel1.add(Easy);
        Easy.setBounds(0, 0, 220, 210);

        medium.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\medium.png")); // NOI18N
        medium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediumMouseClicked(evt);
            }
        });
        jPanel1.add(medium);
        medium.setBounds(-10, 240, 660, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\vertical-white-notepad-vector-19621512.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 270, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\vertical-white-notepad-vector-19621512.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 0, 250, 420);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\vertical-white-notepad-vector-19621512.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 0, 250, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EasyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyMouseClicked
        // TODO add your handling code here:
        new First_Easy_Level().setVisible(true);
        dispose();
    }//GEN-LAST:event_EasyMouseClicked

    private void HardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardMouseClicked
        // TODO add your handling code here:
        new First_Difficult_Level().setVisible(true);
        dispose();
    }//GEN-LAST:event_HardMouseClicked

    private void mediumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumMouseClicked
        // TODO add your handling code here:
        new First_Medium_Level().setVisible(true);
        dispose();
    }//GEN-LAST:event_mediumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_Difficulty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Easy;
    private javax.swing.JLabel Hard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel medium;
    // End of variables declaration//GEN-END:variables
}
